version: 0.2
phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip index.js index.html
      - echo "updating lambda code"
      - aws lambda update-function-code --function-name myfunction
      - echo "DONE!!"
